PACKAGE_NAME="cytech-t501"
PACKAGE_VERSION="1.0.2"
BUILT_MODULE_NAME[0]="hid-cytech-t501"
DEST_MODULE_LOCATION[0]="/kernel/drivers/hid"
AUTOINSTALL="yes"
MAKE[0]="make LLVM=1 KDIR=/lib/modules/$kernelver/build"
CLEAN="make LLVM=1 clean"
